spring:
  jmx:
    enabled: true
  devtools:
    restart:
      enabled: true
  rabbitmq:
    host: localhost
    port: 61613 #порт для общения по протоколу stomp
    username: guest
    password: guest
server:
  port: 8080
max:
  value:
    cpu: 8